### ISSUE TITLE
Ipyaladin does not run in VSCode but does in Jupyter.

### ISSUE THREAD

**Issue by JosephKarpinski** [cds-astro/ipyaladin#31] opened 2022-03-09 19:08 UTC
Requires JavaScript update

![347855CA-792F-4307-BE04-CE5FD0F8D170](https://user-images.githubusercontent.com/37123616/157513812-5f4f1f89-82a9-4808-b27c-e21c8b152af2.jpeg)

**Comment by bmatthieu3** [comment] 2022-12-06 15:11
Hi @JosephKarpinski,

I uploaded a new version of ipyaladin on npm and thus could be accessed from jsdelivr: https://cdn.jsdelivr.net/npm/ipyaladin@0.2.1/

Maybe you could:
1. upgrade your ipyaladin version with: pip install -U ipyaladin . It should download version 0.2.1
2. retry with vscode, (do not forget to choose the good python kernel where the new ipyaladin v0.2.1 is installed)

**Comment by JosephKarpinski** [comment] 2022-12-06 22:27
Tried to reply with screen prints but your mail server rejected it as to large.

Mixed results. Worked once under Python 3.8.5 but not for a second image.

Did not work under Python 3.11.
Version 0.1.9 works under Python 3.11.

For both above not working cases, nothing is returned.

Will try sending screen prints separately.

**Comment by JosephKarpinski** [comment] 2022-12-06 22:29
Screen prints #1

**Comment by JosephKarpinski** [comment] 2022-12-06 22:32
Screen print #2

**Comment by JosephKarpinski** [comment] 2022-12-06 22:37
Screen print #4

**Comment by JosephKarpinski** [comment] 2022-12-06 22:38
Screen print #5

**Comment by JosephKarpinski** [comment] 2022-12-06 22:38
Screen print #6

**Comment by bmatthieu3** [comment] 2022-12-07 08:22
Hi @JosephKarpinski,

I cannot see your screenshots. Maybe you could send them directly in this github post. What is interesting for me is just for the version 0.2.1 because this is the version I pushed to npm (as you can see here https://www.npmjs.com/package/ipyaladin) and I suppose VSCode is looking for it through jsdelivr or unpkg. Therefore this is the version that has the most of chance to work.
Also be very aware to use the good python kernel inside your VSCode (you can maybe do a !pip list command (or !conda list if you are using conda) to see whether ipyaladin 0.2.1 is the version installed for this python environnement/kernel)

Thank you very much your testing time.

**Comment by JosephKarpinski** [comment] 2022-12-08 15:58
<img width="1412" alt="38DF6748-79F7-449F-9178-40D73413DDF5" src="https://user-images.githubusercontent.com/37123616/206496236-a3680fbd-6687-439f-9364-ac4c082dc30e.png">

**Comment by JosephKarpinski** [comment] 2022-12-08 16:03
But sometimes Version 0.1.11 does not work.
Returns nothing.

<img width="1412" alt="E384EB4F-4816-4D8D-ADAE-BAD4E6EFA2D3" src="https://user-images.githubusercontent.com/37123616/206497248-0aeee372-896a-463a-8b81-5c568851afcc.png">

**Comment by JosephKarpinski** [comment] 2022-12-08 16:05
Does not work under Python 3.11
<img width="1412" alt="2C1680CA-6FCE-4EBE-B11D-BE6EE0E42602" src="https://user-images.githubusercontent.com/37123616/206498009-d7c607ae-1181-48ae-844b-2c3504932d86.png">

**Comment by JosephKarpinski** [comment] 2022-12-08 16:06
Version 0.1.9 works under Python 3.11

<img width="1412" alt="9C29B875-7497-4CD8-848F-146D114053DC" src="https://user-images.githubusercontent.com/37123616/206498425-4544689e-6c28-45ef-8e40-afce641f3d51.png">

**Comment by JosephKarpinski** [comment] 2022-12-08 16:08
Will try pip install ipyaladin==0.2.1 next.

**Comment by JosephKarpinski** [comment] 2022-12-08 16:24
<img width="1381" alt="2700A8AF-CCE3-4D7E-9E11-CAADB5945AED" src="https://user-images.githubusercontent.com/37123616/206504874-2093fe5b-d3ef-4729-98e2-1f69cec633bd.png">

<img width="1381" alt="8B3C5A05-45B0-4358-AB1E-1C1C20CED75D" src="https://user-images.githubusercontent.com/37123616/206504891-cc03930d-621c-4f24-b78c-6a8b7f551884.png">

**Comment by JosephKarpinski** [comment] 2022-12-08 16:25
<img width="1381" alt="7B74F312-32A2-4230-BE21-D35CD7C71D2D" src="https://user-images.githubusercontent.com/37123616/206505601-509ecff1-b437-48f8-bc47-26dcf9a576c4.png">

**Comment by bmatthieu3** [comment] 2022-12-11 17:27
@JosephKarpinski . Awesome for the version 0.2.1! I think the target problem is linked to the Sesame service (i.e. the service responsible for matching a name with a position) which responds slowly.

**Comment by bmatthieu3** [comment] 2022-12-21 14:24
I close this issue as it seems to work with the 0.2.1. Please do not hesitate to reopen it if someone still has trouble running ipyaladin inside VSCode.

**Comment by SultanOrazbayev** [comment] 2024-02-05 02:25
I'm using ipyaladin==0.2.5 and vscode 1.86.0, but unable to get `ipyaladin` to work. Here's more information from my vscode:

Version: 1.86.0 (Universal)
Commit: 05047486b6df5eb8d44b2ecd70ea3bdf775fd937
Date: 2024-01-31T10:29:15.765Z
Electron: 27.2.3
ElectronBuildId: 26495564
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.3.0

In terms of output I only see a thin white line in the output screen.

**Comment by ManonMarchand** [comment] 2024-02-06 11:31
Thanks for reporting! I can reproduce. We're investigating

**Comment by ManonMarchand** [comment] 2024-02-16 14:19
I'm very sorry but I couldn't do anything. The issue is with vscode that does not support the version of ipywidget that we use, see this issue:

https://github.com/microsoft/vscode-jupyter/issues/11336

I hope you can work with either Jupyter or Colab?

**Comment by SultanOrazbayev** [comment] 2024-02-16 14:35
Of course, @ManonMarchand ! Thank you for looking into this! :)

**Closed** 2024-03-15 13:10 UTC
Labels: bug, upstream

**Comment by ManonMarchand** [comment] 2024-03-15 14:45
Should be good in the version 0.3.0, please let me know if there are still some issues

**Comment by SultanOrazbayev** [comment] 2024-03-15 18:42
Tested it just now, works very well! Thank you very much @ManonMarchand !
